### ISSUE TITLE
The crate is unsound

### ISSUE THREAD

**Issue by Kixunil** [RustyYato/out-ref#1]
This writes a value to invalid memory address without requiring `unsafe`:

```rust
Out::from_raw(1usize as *mut u32).set(42);
```

Suggested solution:
Make `from_raw` `unsafe`.
For convenience impl `From<&'a mut MaybeUninit<T>> for OutRef<'a, T>`

**Comment by RustyYato** [comment]
Ouch, I thought I had made that `unsafe`, thanks for the issue.

**Comment by RustyYato** [comment]
Oh, this crate, I completely forgot about this. I don't recommend using this crate at all. I'll update the README and documentation accordingly.

**Comment by Kixunil** [comment]
Thanks for quick feedback!

I still think that something like this would be useful because many people get this wrong. Having a well-reviewed crate would be very helpful. If you don't have time to maintain it, then maybe offer it for others to take? (I'm not myself confident in having time to maintain it in the near future.)

I was also thinking it'd be best to have language-level construct with checking etc but it's pretty hard. It requires guaranteeing absence of leaks. (At least in *some code*)

**Comment by RustyYato** [comment]
I'm fine with making the required fixes to get this correct, but I won't be adding any new features. I'll update the README to clarify this.
